### PR TITLE
Updated models.py to include rounded price

### PR DESCRIPTION
**Pull request by Scriptodude**
The "arrondir_prix" method rounds a price to the nearest 5 cents.

Ex: 
- 0.04 becomes 0.05
- 0.08 becomes 0.10
- 10.03 becomes 10.05
- 10.05 stays 10.05

### CODE REVIEW

**Comment by ventilooo** [comment]
I need you to add unit test for this PR and  update  #9 to know if the build is succesfull

**Comment by Scriptodude** [comment]
Will do once i have an actual Unix environment accessible ^_^

**Comment by Scriptodude** [comment]
J'ai réussi à upgraded EnceFAL vers la version 1.9.6 de django, le serveur launch et le programme build, mais il n'est pas fonctionnel encore. 
J'ai le repository local sur ma machine, j'upload ça au courant de la semaine sur github, et je fait le pr ensuite !
Quelques dizaines d'heures de "plaisir" ^_^ .

**Comment by ventilooo** [comment]
Great news !
Please, separate your PR by logical addition to the project or by issue.
- One PR for the upgrade to django 1.9.6
- Another one for the rounded price.
- etc ...

**Pull request closed without merging**
